### ISSUE TITLE
TimeoutError while downloading the blacklist

### ISSUE THREAD

**Issue by niutech** [ubports/system-image#15]
I wanted to upgrade my bq Aquaris E4.5 (Krillin) from OTA-14 to OTA-15, so I run `sudo system-image-cli -v -p 0 --progress dots` in `adb shell`, as stated in the [blog post](https://ubports.com/pl/blog/ubports-blogi-i-wiadomosci-1/post/ubuntu-touch-ota-15-release-3736). However, I get a timeout error while downloading the blacklist:
```
[systemimage] Jan 30 17:53:21 2021 (10509) running state machine [ubports-touch/16.04/stable/krillin]
[systemimage] Jan 30 17:53:22 2021 (10509) Looking for blacklist: https://system-image.ubports.com/gpg/blacklist.tar.xz
[systemimage] Jan 30 17:53:22 2021 (10509) [0xb54c22d0] Requesting group download:
        https://system-image.ubports.com/gpg/blacklist.tar.xz -> /var/lib/system-image/keyring.tar.xz
        https://system-image.ubports.com/gpg/blacklist.tar.xz.asc -> /var/lib/system-image/keyring.tar.xz.asc

[systemimage] Jan 30 17:53:22 2021 (10509) Allow GSM? No
[systemimage] Jan 30 17:53:22 2021 (10509) [/com/canonical/applications/download/000e991f18a24bd0af2eb3f38bf0827f] Running group download reactor
[systemimage] Jan 30 17:53:22 2021 (10509) self: <UDMDownloadManager at 0xb54c22d0>, self._iface: <Interface <ProxyObject wrapping <dbus._dbus.SystemBus (system) at 0xb6393a50> :1.122 /com/canonical/applications/download/000e991f18a24bd0af2eb3f38bf0827f at 0xb54c2310> implementing 'com.canonical.applications.GroupDownload' at 0xb54c21d0>
[systemimage] Jan 30 18:03:22 2021 (10509) [/com/canonical/applications/download/000e991f18a24bd0af2eb3f38bf0827f] Group download reactor done
[systemimage] Jan 30 18:03:22 2021 (10509) uncaught exception in state machine
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/systemimage/state.py", line 133, in __next__
    step()
  File "/usr/lib/python3/dist-packages/systemimage/state.py", line 219, in _get_blacklist_1
    get_keyring('blacklist', url, 'image-master')
  File "/usr/lib/python3/dist-packages/systemimage/keyring.py", line 107, in get_keyring
    (ascxz_src, ascxz_dst),
  File "/usr/lib/python3/dist-packages/systemimage/download.py", line 209, in get_files
    self._get_files(records, pausable, signal_started)
  File "/usr/lib/python3/dist-packages/systemimage/udm.py", line 179, in _get_files
    raise TimeoutError
TimeoutError
Exception occurred during update; see log file for details
[systemimage] Jan 30 18:03:22 2021 (10509) system-image-cli exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/systemimage/main.py", line 402, in main
    list(state)
  File "/usr/lib/python3/dist-packages/systemimage/state.py", line 133, in __next__
    step()
  File "/usr/lib/python3/dist-packages/systemimage/state.py", line 219, in _get_blacklist_1
    get_keyring('blacklist', url, 'image-master')
  File "/usr/lib/python3/dist-packages/systemimage/keyring.py", line 107, in get_keyring
    (ascxz_src, ascxz_dst),
  File "/usr/lib/python3/dist-packages/systemimage/download.py", line 209, in get_files
    self._get_files(records, pausable, signal_started)
  File "/usr/lib/python3/dist-packages/systemimage/udm.py", line 179, in _get_files
    raise TimeoutError
TimeoutError
[systemimage] Jan 30 18:03:22 2021 (10509) state machine finished
```
That said, downloading this file by `wget https://system-image.ubports.com/gpg/blacklist.tar.xz` succeeds. What is going on?

**Comment by niutech** [comment]
OK, now I realized that it was due to my network connection being 3G and in the log there is `Allow GSM? No`. When I connected to the WiFi network, the update succeeds.
